version: '3'

services:
    # MongoDB for DB1
    mongo:
        ports:
            - 27017:27017
        image: mongo
        logging:
            driver: none
    # GraphQL API for DB1
    mongoke:
        ports:
            - 4000:80
        image: mongoke/mongoke
        environment:
            - DB_URL=mongodb://mongo/db
        volumes:
            - ./graphql/mongoke.yml:/conf.yml
            - ./graphql/schema.graphql:/schema.graphql
        links:
            - "mongo:mongo"    

    # MongoDB for DB2
    mongo2:
        ports:
            - 27018:27017
        image: mongo
        logging:
            driver: none     
    # GraphQL API for DB2
    mongoke2:
        ports:
            - 4001:80
        image: mongoke/mongoke
        environment:
            - DB_URL=mongodb://mongo2:27017/db
        volumes:
            - ./graphql/mongokeCacheServer.yml:/conf.yml
            - ./graphql/schemaCacheServer.graphql:/schema.graphql
        links:
            - "mongo2:mongo2"    
    # ReactJS Application (DB1 and 2)
    react:
        build: ./react/
        ports:
            - 3000:3000
        stdin_open: true
    
    # Fake data generator
    populator:
        build: ./populator/
        volumes:
            - ./populator:/app          
        depends_on: 
            - mongo        
        links:
            - "mongo:mongo"
            
    # Cache server to calculate ratings for suppliers
    cacheserver:
        ports:
            - 3002:3002
        build: ./db2server/
        volumes:
            - ./db2server:/app          
        depends_on: 
            - mongo2  
            - mongoke     
            - mongoke2        
        links:
            - "mongo2:mongo2"
            - "mongoke:mongoke"                  