version: '3'

services:
    mongoke:
        ports:
            - 4000:80
        image: mongoke/mongoke
        environment:
            - DB_URL=mongodb://mongo/db
        volumes:
            - ./graphql/mongoke.yml:/conf.yml
            - ./graphql/schema.graphql:/schema.graphql
        links:
            - "mongo:mongo"    
    mongo:
        ports:
            - 27017:27017
        image: mongo
        logging:
            driver: none

    mongoke2:
        ports:
            - 4001:80
        image: mongoke/mongoke
        environment:
            - DB_URL=mongodb://mongo2:27017/db
        volumes:
            - ./graphql/mongokeCacheServer.yml:/conf.yml
            - ./graphql/schemaCacheServer.graphql:/schema.graphql
        links:
            - "mongo2:mongo2"    
    mongo2:
        ports:
            - 27018:27017
        image: mongo
        logging:
            driver: none     

    react:
        build: ./react/
        ports:
            - 3000:3000
        stdin_open: true
    populator:
        build: ./populator/
        volumes:
            - ./populator:/app          
        depends_on: 
            - mongo        
        links:
            - "mongo:mongo"    
    cacheserver:
        ports:
            - 3002:3002
        build: ./db2server/
        volumes:
            - ./db2server:/app          
        depends_on: 
            - mongo2  
            - mongoke     
            - mongoke2        
        links:
            - "mongo2:mongo2"
            - "mongoke:mongoke"                  

    # populate-db:
    #     image: mongoke/populate-mongo
    #     volumes:
    #         - ./mongoke.yml/:/conf.yml
    #         - ./schema.graphql:/schema.graphql
    #     environment:
    #         - DB_URL=mongodb://mongo/db
    #         - DOCUMENTS_PER_COLLECTION=100
    #     depends_on: 
    #         - mongo