version: '3'

services:
    mongoke:
        ports:
            - 4000:80
        image: mongoke/mongoke
        environment:
            - DB_URL=mongodb://mongo/db
        volumes:
            - ./mongoke.yml:/conf.yml
            - ./schema.graphql:/schema.graphql
    mongo:
        image: mongo
        logging:
            driver: none
    populate-db:
        image: mongoke/populate-mongo
        volumes:
            - ./mongoke.yml/:/conf.yml
            - ./schema.graphql:/schema.graphql
        environment:
            - DB_URL=mongodb://mongo/db
            - DOCUMENTS_PER_COLLECTION=100
        depends_on: 
            - mongo